config/routes.rb
require 'resque/server'
Credibles::Application.routes.draw do

  mount Resque::Server.new => '/resque'

  resources :pages
  resources :edits

  resource :session

end

app/views/layouts/application.html.haml
!!!
%head
  %title copypasta: reader powered edits
  =stylesheet_link_tag 'app'
  %noscript
    %style{:type => 'text/css'}
      :plain
        .no-js{ display: auto; }
        .js{ display: none !important; }
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20906606-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
%body
  #container{ :class => (yield :page_type).strip }
    %h1#logo
      %span copypasta
    #content
      =yield
      =javascript_include_tag 'jquery-1.5.1'
      =javascript_include_tag 'app'

app/views/layouts/copypasta.html.haml
!!!
%head
  %title copypasta: reader powered edits
  =stylesheet_link_tag 'compiled/app'
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20906606-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
%body
  #container
    %h1#logo
      %span copypasta
    #content
      =yield
      =javascript_include_tag 'jquery-1.4.4.min'
      =javascript_include_tag 'application'
      #copy-pasta-button= image_tag "button-light.png", :alt => 'Suggest changes'
      :plain
        <script type="text/javascript">
          copypasta_content_selector = '#content';
          copypasta_account_id = '9';
          #{yield :button_options }</script>
      %script{:type => 'text/javascript', :src => '/javascripts/copypasta.js'}

app/views/layouts/dialog.html.haml
=yield

app/views/layouts/editor_email.text.erb
<%=yield%>

***copypasta instructions***
Manage page edits: <%= new_session_url(:key => @token.key, :url => page_url(@edit.page)) %>

app/views/layouts/framed.html.haml
!!! 5
%html
  %head
    %title Framed copypasta
    =stylesheet_link_tag 'framed'
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20906606-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

  %body#copy-pasta-frame{:class => (yield :frame_type).strip}
    -flash.each do |k,v|
      %div{:class => k}= v
    -if @errors
      .error
        %ul
          -@errors.keys.each do |f|
            -@errors[f].each do |e|
              %li
                = f.to_s.humanize
                = e
    =yield
    =javascript_include_tag 'jquery-1.4.4.min'
    =javascript_include_tag 'framed'
    :javascript
      parent_url = '#{escape_javascript params[:url]}';